version: "3.6"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/petsafetydb_dev
      - DATABASE_TEST_URL=postgresql+psycopg2://postgres:postgres@db:5432/petsafetydb_test
    command: python manage.py run -h 0.0.0.0
