version: "3.6"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql+psycopg2://dduamhlultypyf:6870a4d8a926f91d750f9ff419f1b4aff119afe16d8577bd51c3e4d1ada1ba12@ec2-34-194-158-176.compute-1.amazonaws.com:5432/dakodh4mdegc4h
      - DATABASE_TEST_URL=postgresql+psycopg2://postgres:postgres@localhost:3306/petsafety
    command: python manage.py run -h 0.0.0.0
